import Head from "next/head";
import { useEffect, useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import axios from "axios";

import Layout from "../Layout";

import SwiperLg from "../components/custom/SwiperLg";
import BookCategory from "../components/custom/BookCategory";
import BannerSwiper from "../components/custom/BannerSwiper";

import { fetchBooks } from "../src/redux/slices/booksSlice";

export default function Home() {
<<<<<<< Updated upstream
  const [blogBanners, setBlogBanners] = useState([]);
  const [quoteBanners, setQuoteBanners] = useState([]);
=======
<<<<<<< Updated upstream
=======
  const [blogBanners, setBlogBanners] = useState([]);
  const [quoteBanners, setQuoteBanners] = useState([]);
  const [booksOfFirstCategory, setBooksOfFirstCategory] = useState([]);
  const [booksOfSecondCategory, setBooksOfSecondCategory] = useState([]);
>>>>>>> Stashed changes
  const books = useSelector((store) => store.books);
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(fetchBooks());
  }, []);

  useEffect(() => {
<<<<<<< Updated upstream
    const fetchBanners = async () => {
      const res = await axios.get("/api/banners");
      const banners = res.data;
      setBlogBanners(banners.filter(banner => banner.category === "blog"));
      setQuoteBanners(banners.filter(banner => banner.category === "quote"));
    };
    fetchBanners();
  }, []);
=======
    if (books.status === "success") {
      let temp = books.value.filter(
        (book) => book.subCategory === "توسعه فردی"
      );
      setBooksOfFirstCategory(temp);
      temp = books.value.filter(
        (book) => book.subCategory === "خانواده و ازدواج"
      );
      setBooksOfSecondCategory(temp);
    }
  }, [books.status]);

  useEffect(() => {
    const fetchBanners = async () => {
      const res = await axios.get("/api/banners");
      const banners = res.data;
      setBlogBanners(banners.filter((banner) => banner.category === "blog"));
      setQuoteBanners(banners.filter((banner) => banner.category === "quote"));
    };
    fetchBanners();
  }, []);
>>>>>>> Stashed changes
>>>>>>> Stashed changes
  return (
    <>
      <Head>
        <title>طاقچه | فروشگاه کتاب</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/logo.svg" />
      </Head>
<<<<<<< Updated upstream
      <Layout>
        <SwiperLg />
        <BookCategory title="توسعه فردی" books={books.value} />
        <BannerSwiper banners={blogBanners} />
=======
<<<<<<< Updated upstream

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
=======
      <Layout>
        <SwiperLg />
        <BookCategory title="توسعه فردی" books={booksOfFirstCategory} />
        <BannerSwiper banners={blogBanners} />
        <BookCategory title="خانواده و ازدواج" books={booksOfSecondCategory} />
>>>>>>> Stashed changes
        <BannerSwiper banners={quoteBanners} />
      </Layout>
    </>
  );
<<<<<<< Updated upstream
=======
>>>>>>> Stashed changes
>>>>>>> Stashed changes
}
