import Head from "next/head";
import { useEffect, useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import axios from "axios";

import Layout from "../Layout";

import SwiperLg from "../components/custom/SwiperLg";
import BookCategory from "../components/custom/BookCategory";
import BannerSwiper from "../components/custom/BannerSwiper";

import { fetchBooks } from "../src/redux/slices/booksSlice";

export default function Home() {
  const [blogBanners, setBlogBanners] = useState([]);
  const [quoteBanners, setQuoteBanners] = useState([]);
  const books = useSelector((store) => store.books);
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(fetchBooks());
  }, []);

  useEffect(() => {
    const fetchBanners = async () => {
      const res = await axios.get("/api/banners");
      const banners = res.data;
      setBlogBanners(banners.filter(banner => banner.category === "blog"));
      setQuoteBanners(banners.filter(banner => banner.category === "quote"));
    };
    fetchBanners();
  }, []);
  return (
    <>
      <Head>
        <title>طاقچه | فروشگاه کتاب</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos/logo.svg" />
      </Head>
      <Layout>
        <SwiperLg />
        <BookCategory title="توسعه فردی" books={books.value} />
        <BannerSwiper banners={blogBanners} />
        <BannerSwiper banners={quoteBanners} />
      </Layout>
    </>
  );
}
